/*
-- 계정생성
CREATE USER C##TOY IDENTIFIED BY "1234";
-- 권한부여
GRANT CONNECT, RESOURCE TO C##TOY;
ALTER USER C##TOY DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS; -- INSERT시 오류 방지
*/

SET AUTOCOMMIT OFF;
------------------------------------------------------------------------------------------------------

DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    MEMBER_NO       NUMBER          PRIMARY KEY
    , MEMBER_ID     VARCHAR2(16)    UNIQUE NOT NULL
    , MEMBER_PWD    VARCHAR2(24)    NOT NULL
    , MEMBER_NICK   VARCHAR2(30)    NOT NULL
    , ADDRESS       VARCHAR2(50)
);
DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;

INSERT INTO MEMBER (MEMBER_NO,MEMBER_ID, MEMBER_PWD, MEMBER_NICK, ADDRESS) VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user01', '1234', 'firstMan', '127.0.0.1');

SELECT MEMBER_NO, MEMBER_ID, MEMBER_NICK FROM MEMBER WHERE MEMBER_ID = 'user01' AND MEMBER_PWD = '1234';

select * from member;

DROP TABLE CHAT_ARCHIVE CASCADE CONSTRAINTS;
CREATE TABLE CHAT_ARCHIVE (
    CHAT_NO             NUMBER              PRIMARY KEY
    , CHAT_SENDER       NUMBER
    , CHAT_RECEIVER     NUMBER
    , CHAT_CONTENT      VARCHAR2(1500)
    , CHAT_ENROLL_DATE  TIMESTAMP           DEFAULT SYSDATE
    , CHAT_READ         CHAR(1)             DEFAULT '1'
);

ALTER TABLE CHAT_ARCHIVE ADD CONSTRAINT FK_CHAT_SENDER FOREIGN KEY(CHAT_SENDER) REFERENCES MEMBER(MEMBER_NO);
ALTER TABLE CHAT_ARCHIVE ADD CONSTRAINT FK_CHAT_RECEIVER FOREIGN KEY(CHAT_RECEIVER) REFERENCES MEMBER(MEMBER_NO);
ALTER TABLE CHAT_ARCHIVE ADD CONSTRAINT CHECK_CHAT_READ CHECK ( CHAT_READ IN ('1' , '0' ) );

DROP SEQUENCE SEQ_CHAT_NO;
CREATE SEQUENCE SEQ_CHAT_NO NOCACHE NOCYCLE;


SELECT MEMBER_NICK
FROM MEMBER
WHERE MEMBER_NICK = 'dlwlrma';


INSERT INTO CHAT_ARCHIVE VALUES(
        SEQ_CHAT_NO.NEXTVAL
    ,   (SELECT MEMBER_NO
        FROM MEMBER
        WHERE MEMBER_NICK = ?)
    , (SELECT MEMBER_NO
        FROM MEMBER
        WHERE MEMBER_NICK = ?)
    ,   ?
    ,   DEFAULT
    ,   DEFAULT
);

select * from chat_archive;