/*
-- 계정생성
CREATE USER C##TOY IDENTIFIED BY "1234";
-- 권한부여
GRANT CONNECT, RESOURCE TO C##TOY;
ALTER USER C##TOY DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS; -- INSERT시 오류 방지
*/

SET AUTOCOMMIT OFF;
------------------------------------------------------------------------------------------------------

DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    MEMBER_NO       NUMBER          PRIMARY KEY
    , MEMBER_ID     VARCHAR2(16)    UNIQUE NOT NULL
    , MEMBER_PWD    VARCHAR2(24)    NOT NULL
    , MEMBER_NICK   VARCHAR2(30)    NOT NULL
    , ADDRESS       VARCHAR2(50)
);
DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO;

INSERT INTO MEMBER (MEMBER_NO,MEMBER_ID, MEMBER_PWD, MEMBER_NICK, ADDRESS) VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user01', '1234', 'firstMan', '127.0.0.1');

SELECT MEMBER_NO, MEMBER_ID, MEMBER_NICK FROM MEMBER WHERE MEMBER_ID = 'user01' AND MEMBER_PWD = '1234';

select * from member;


DROP TABLE CHAT_ROOM CASCADE CONSTRAINTS;
CREATE TABLE CHAT_ROOM (
    CHAT_ROOM_NO        NUMBER          PRIMARY KEY
    , CHAT_ROOM_NAME    VARCHAR2(100)   NOT NULL
    , CHAT_ROOM_MAX     NUMBER          NOT NULL
);

DROP SEQUENCE SEQ_CHAT_ROOM_NO;
CREATE SEQUENCE SEQ_CHAT_ROOM_NO;

insert into CHAT_ROOM VALUES( SEQ_CHAT_ROOM_NO.nextval, 'test_other' , 4);
COMMIT;

DROP TABLE CHAT_ARCHIVE CASCADE CONSTRAINTS;
CREATE TABLE CHAT_ARCHIVE (
    CHAT_NO             NUMBER          PRIMARY KEY
    , CHAT_ROOM_NO      NUMBER
    , CHAT_SENDER       NUMBER
    , CHAT_CONTENT      VARCHAR2(1500)
    , CHAT_ENROLL_DATE  TIMESTAMP       DEFAULT SYSDATE
);

ALTER TABLE CHAT_ARCHIVE ADD CONSTRAINT FK_CHAT_ROOM_ARCHIVE FOREIGN KEY(CHAT_ROOM_NO) REFERENCES CHAT_ROOM(CHAT_ROOM_NO);
ALTER TABLE CHAT_ARCHIVE ADD CONSTRAINT FK_CHAT_ARCHIVE_MEMBER FOREIGN KEY(CHAT_SENDER) REFERENCES MEMBER(MEMBER_NO);

DROP SEQUENCE SEQ_CHAT_ARCHIVE_NO;
CREATE SEQUENCE SEQ_CHAT_ARCHIVE_NO;

INSERT INTO CHAT_ARCHIVE VALUES ( SEQ_CHAT_ARCHIVE_NO.NEXTVAL, ?, ?, ?, DEFAULT );

SELECT CHAT_NO, CHAT_SENDER, CHAT_CONTENT, CHAT_ENROLL_DATE FROM CHAT_ARCHIVE WHERE CHAT_ROOM_NO = 1;

